FROM nginx:latest

# Remove the default configuration file
#RUN rm /etc/nginx/conf.d/default.conf

# Copy your custom configuration file to the container
#COPY nginx.conf /etc/nginx/conf.d/

# Copy any static content to the container (optional)
#COPY static-content /usr/share/nginx/html/

# Expose ports
EXPOSE 80
EXPOSE 443

# Start NGINX
CMD ["nginx", "-g", "daemon off;"]
