version: '3.8'

services:
  db:
    build: ./requirements/mariadb/.
    # image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootjjangpass5%@4
      MARIADB_DATABASE: testdb1
      MARIADB_USER: Dave
      MARIADB_PASSWORD: Davejjang3#3@
  wordpress:
    build: ./requirements/wordpress/.
    # image: wordpress:php8.1-fpm
    depends_on:
      - db
    volumes:
      - wp_data:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: testdb1
      WORDPRESS_DB_USER: Dave
      WORDPRESS_DB_PASSWORD: Davejjang3#3@
  nginx:
    build: ./requirements/nginx/.
    # image: nginx:latest
    depends_on:
      - wordpress
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - wp_data:/var/www/html
      # - ./requirements/nginx/tools/nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  db_data:
  wp_data:
