version: '3.8'

services:
  mariadb:
    container_name: db
    build: ./requirements/mariadb
    restart: always
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception
  wordpress:
    container_name: wp
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    restart: always
    env_file: .env
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception
  nginx:
    container_name: nx
    build:
      context: ./requirements/nginx
      args:
        - DOMAIN_NAME=${DOMAIN_NAME}
    depends_on:
      - wordpress
    ports:
      - 443:443
    restart: always
    env_file: .env
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception

volumes:
    wp_data:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: ${HOME}/data/wp
    db_data:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: ${HOME}/data/db

networks:
    inception:
        driver: bridge
