version: '3.8'

services:
  db:
    #build: .
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootjjangpass5%@4
      MYSQL_DATABASE: testdb1
      MYSQL_USER: Dave
      MYSQL_PASSWORD: Davejjang3#3@
  wordpress:
    #build: .
    image: wordpress:latest
    depends_on:
      - db
    volumes:
      - wp_data:/var/www/html/wp-content
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: testdb1
      WORDPRESS_DB_USER: Dave
      WORDPRESS_DB_PASSWORD: Davejjang3#3@
  nginx:
    build: ./requirements/nginx/.
    # image: nginx:latest
    depends_on:
      - wordpress
    ports:
      - 80:80
    restart: always
    volumes:
      - ./requirements/nginx/tools/nginx.conf:/etc/nginx/conf.d/wordpress.conf:ro

volumes:
  db_data:
  wp_data:
