# Use the official PHP image with FPM and Nginx as the base image
FROM wordpress:php7.4-fpm

# Install Nginx
# RUN apt-get update && \
#     apt-get install -y nginx && \
#     apt-get clean && \
#     rm -rf /var/lib/apt/lists/*

# Copy Nginx configuration file
# COPY nginx.conf /etc/nginx/sites-available/default

# Expose Nginx port
# EXPOSE 80

# Run Nginx and PHP-FPM
# CMD ["sh", "-c", "service php7.4-fpm start; service nginx start; tail -F /var/log/nginx/access.log"]
