version: '3'

services:
    nginx:
        container_name: nginx
        restart: always
        build: ./requirements/nginx
        ports:
            - '443:443'
        networks:
            - inception
        volumes:
            - WP:/var/www/html/
        depends_on:
            - wordpress

    mariadb:
        container_name: mariadb
        restart: always
        build: ./requirements/mariadb
        expose:
            - '3306'
        env_file:
            - .env
        tty: true
        volumes:
            - DB:/var/lib/mysql
        networks:
            - inception

    wordpress:
        restart: always
        container_name: wordpress
        build: ./requirements/wordpress
        tty: true
        expose:
            - '9000'
        depends_on:
            - mariadb
        env_file:
            - .env
        volumes:
            - WP:/var/www/html
        networks:
            - inception

volumes:
    WP:
        # driver: local
        # driver_opts:
        #     type: none
        #     # device: /home/jinbekim/data/wp
        #     device: ./data/wp
        #     o: bind
    DB:
        # driver: local
        # driver_opts:
        #     type: none
        #     # device: /home/jinbekim/data/db
        #     device: ./data/db
        #     o: bind

networks:
    inception:
        driver: bridge